# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Runs unit tests"
  lane :tests do
    params = {
      package_path: '.',
      scheme: 'StatusList',
      devices: ['iPhone 14'], 
      result_bundle: true,
      parallel_testing: false,
      xcodebuild_formatter: "xcbeautify"
    }

    if ENV['CI'] 
      params[:xcargs] = "-skipPackagePluginValidation"
    end

    run_tests(params)
  end

  desc "Builds the package"
  lane :just_build do
    xcodebuild(
      scheme: "StatusList",
      destination: "platform=iOS Simulator,OS=16.2,name=iPhone 8",
      xcargs: "-skipPackagePluginValidation -disableAutomaticPackageResolution"
    )
  end
  
end
